const get_level = () => {
  /** @type {String[]} */
  const map = [
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
    "r  r c                             c             r",
    "r                                          e     r",
    "r             r                                  r",
    "r       e                         e              r",
    "r                        c                       r",
    "r                                                r",
    "r       c                           r            r",
    "r                                                r",
    "r                                                r",
    "r    c                   c                       r",
    "r            r                     c             r",
    "r                                                r",
    "r                                                r",
    "r                                     c          r",
    "r                      p                         r",
    "r      e  c                                      r",
    "r                                           e    r",
    "r                                                r",
    "r                                   r            r",
    "r          r                                     r",
    "r                        c                       r",
    "r                                                r",
    "r                                                r",
    "r                                  c             r",
    "r                        r                       r",
    "r         c                                      r",
    "r                                                r",
    "r                                                r",
    "r    c           c              e     c          r",
    "r                                                r",
    "r                                                r",
    "r                                                r",
    "r                 e                              r",
    "r                        c                       r",
    "r         c                                      r",
    "r                                   r            r",
    "r                                                r",
    "r                                                r",
    "r                                  c             r",
    "r      e        r           e                    r",
    "r                                                r",
    "r                                           e    r",
    "r                                                r",
    "r                     e      r                   r",
    "r                                                r",
    "r      e    c                                    r",
    "r                                                r",
    "r                                     c          r",
    "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr",
  ]

  return map
}
