const get_level = () => {
  /** @type {String[]} */
  const map = [
    "   r                                              ",
    "     c                             c              ",
    "                                           e      ",
    "              r                                   ",
    "        e                         e               ",
    "                         c                        ",
    "                                                  ",
    "        c                           r             ",
    "                                                  ",
    "                                                  ",
    "     c                   c                        ",
    "             r                     c              ",
    "                                                  ",
    "                                                  ",
    "                                      c           ",
    "                       p                          ",
    "       e  c                                       ",
    "                                            e     ",
    "                                                  ",
    "                                    r             ",
    "           r                                      ",
    "                         c                        ",
    "                                                  ",
    "                                                  ",
    "                                   c              ",
    "                         r                        ",
    "          c                                       ",
    "                                                  ",
    "                                                  ",
    "     c           c              e     c           ",
    "                                                  ",
    "                                                  ",
    "                                                  ",
    "                  e                               ",
    "                         c                        ",
    "          c                                       ",
    "                                    r             ",
    "                                                  ",
    "                                                  ",
    "                                   c              ",
    "       e        r           e                     ",
    "                                                  ",
    "                                            e     ",
    "                                                  ",
    "                      e      r                    ",
    "                                                  ",
    "       e    c                                     ",
    "                                                  ",
    "                                      c           ",
    "                                                  ",
  ]

  return map
}
