const get_level = () => {
  /** @type {String[]} */
  const map = [
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "b  r c                             c             b",
    "b                         r                e     b",
    "b             r                                  b",
    "b       e                         e              b",
    "b                        c                       b",
    "b                r                               b",
    "b       c                           r    r       b",
    "b                  r      r                      b",
    "b                                                b",
    "b    c                   c                       b",
    "b            r                     c    r        b",
    "b                  r    r  r                     b",
    "b                                                b",
    "b           r                         c          b",
    "b                      p                         b",
    "b      e  c                    r                 b",
    "b     r                 r                   e    b",
    "b                  r                             b",
    "b                                   r            b",
    "b          r    r                                b",
    "b    r                   c                       b",
    "b                                          r     b",
    "b        r      r                                b",
    "b                                  c             b",
    "b                        r              r        b",
    "b     r   c          r         r                 b",
    "b                                                b",
    "b                                                b",
    "b    c           c        r     e     c          b",
    "b                                                b",
    "b                       r                r       b",
    "b    r                              r            b",
    "b                 e                              b",
    "b                        c                       b",
    "b         c                                      b",
    "b                         r         r    r       b",
    "b          r         r                           b",
    "b                                                b",
    "b                                  c             b",
    "b      e        r           e                    b",
    "b                                                b",
    "b               r                  r        e    b",
    "b    r                                           b",
    "b          r          e      r          r        b",
    "b                                                b",
    "b      e    c            r                       b",
    "b                                   r            b",
    "b                 r                   c          b",
    "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  ]

  return map
}
